export const SEND_WEBSOCKET_MESSAGE_SUCCESS = 'SEND_WEBSOCKET_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';
export const SEND_WEBSOCKET_MESSAGE = 'SEND_WEBSOCKET_MESSAGE';
export const INIT_WBESOCKET = 'INIT_WBESOCKET';
export const RECEIVE_SOCKET_WEBSOCKET_MESSAGE = 'RECEIVE_SOCKET_WEBSOCKET_MESSAGE';
